import {jsPDF} from 'jspdf'

let img = 'data:image/jpg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wgARCAAdAB0DASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAcIBv/EABcBAAMBAAAAAAAAAAAAAAAAAAAFBgT/2gAMAwEAAhADEAAAAeFFcNaZLsyp3GWtJiEbshlof//EABwQAAEDBQAAAAAAAAAAAAAAAAEAAhAEBhYgNP/aAAgBAQABBQKcnpdwC4q5+Cf/xAAeEQABAwQDAAAAAAAAAAAAAAAEABESAwUTFCJBgf/aAAgBAwEBPwFW0SmVPJ0yEtu1TyTbxBBacuTuv//EABwRAAIABwAAAAAAAAAAAAAAAAADBBETFCFCYv/aAAgBAgEBPwEjtS+5HvrSwf/EAB8QAAECBgMAAAAAAAAAAAAAAAEQIAIDESEyc5Gx0f/aAAgBAQAGPwJcJ3A9fQXKQbB0Wf/EABcQAQADAAAAAAAAAAAAAAAAAAEgITD/2gAIAQEAAT8hyKGAUoCRj//aAAwDAQACAAMAAAAQ+55D/8QAHREAAgEEAwAAAAAAAAAAAAAAAREAITFBYVFxsf/aAAgBAwEBPxCUpOBFXb8iXMIVVtsTrnhJPZ5n/8QAHxEAAgECBwAAAAAAAAAAAAAAAREAITFBUWGBscHh/9oACAECAQE/EIINevUDh8/JkRPF32n/xAAYEAEAAwEAAAAAAAAAAAAAAAABESAwMf/aAAgBAQABPxDLkh8QKVXgFvf/2Q=='

function generate(text='',filename='',PATH=''){
    let pdf_gen = new jsPDF({'orientation':'landscape','unit':'px','format':'letter'})
    
    pdf_gen.setFontSize(30)
    pdf_gen.setTextColor('#345')
    pdf_gen.text(text,10,100)
    pdf_gen.addImage(img,'JPEG',10,20,30,30)
    pdf_gen.text('forms',50,45)
    pdf_gen.save(PATH+`/pdfs/${filename}.pdf`)
}

export default generate